### ISSUE TITLE
QEDm link doesn't work

### ISSUE THREAD

**Issue by lukeaduncan** [IHE/ITI.mXDE#9]
In volume 1, there are links to QEDm that point to https://profiles.ihe.net/PCC/QEDm/index.html which doesn't exist.  The PCC index page points directly to the PDF.

I think it's probably better to make the link exist with a redirect, so if/when QEDm is converted to an IG, then it will still work.

**Comment by JohnMoehrke** [comment]
We are actively in the process of releasing QEDm as converted to IG. That is release will resolve this.
